api/urls.py
from django.urls import path, include
from api.views import NewsViewSet, StockViewSet, WeatherViewSet 

app_name = 'api'

news_list = NewsViewSet.as_view({ 'get' : 'list' })
news_detail = NewsViewSet.as_view({ 'get' : 'detail' })

stock_list = StockViewSet.as_view({ 'get' : 'list' })
stock_detail = StockViewSet.as_view({ 'get' : 'detail'})

weather_list = WeatherViewSet.as_view({ 'get' : 'list' })
weather_detail = WeatherViewSet.as_view({ 'get' : 'detail' })

urlpatterns = [
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('news/', news_list, name='news_list'),
    path('news/<int:pk>', news_detail, name='news_detail'),
    path('stock/', stock_list, name='stock_list'),
    path('stock/<int:pk>', stock_detail, name='stock_detail'),
    path('weather/', weather_list, name='weather_list'),
    path('weather/<int:pk>', weather_detail, name='weather_detail'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from rest_framework import routers
from news import rest_views

router = routers.DefaultRouter()
router.register(r'users', rest_views.UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('news/', include('news.urls', namespace='news')),
    path('weather/', include('weather.urls', namespace='weather')),
    path('stock/', include('stock.urls', namespace='stock')),

    path('api/', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls', namespace='api')),
]

stock/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import StockLV, StockDV, SearchFormView

app_name = 'stock'

urlpatterns = [
    path('', StockLV.as_view(), name='index'),
    path('list/', StockLV.as_view(), name='list'),
    path('<int:pk>/', StockDV.as_view(), name='detail'),
    path('search/', SearchFormView.as_view(), name='search'),

]

stock/models.py
from django.db import models

class Stock(models.Model):
    objects = models.Manager()
    name = models.CharField('NAME', max_length=30, unique=True)
    code = models.IntegerField('CODE', blank=True)
    price = models.TextField('PRICE', blank=True)
    max_price = models.IntegerField('MAX_PRICE', blank=True, null=True)
    min_price = models.IntegerField('MIN_PRICE', blank=True, null=True)
    saved_time = models.DateTimeField('SAVED_TIME', auto_now_add=True)
    url = models.URLField('URL')

    def __str__(self):
        return self.name + self.url
 
    class Meta:
        verbose_name = 'stock'
        verbose_name_plural = 'stocks'
        db_table = 'stock'
        ordering = ('-saved_time',) # desc,

stock/forms.py
from django import forms
from .models import Stock

class SearchForm(forms.Form):
    search_word = forms.CharField(label = 'Search Stock')

stock/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.db.models import Q
from .models import Stock
from .forms import SearchForm
import os

class StockLV(ListView):
    model = Stock
    template_name = "stock/stock_list.html"
    paginate_by = 10

class StockDV(DetailView):
    model = Stock


class SearchFormView(FormView):
    form_class = SearchForm
    template_name = "stock/stock_search.html"
    success_url = '/stock/search'

    def form_valid(self, form):
        seword = self.request.POST['search_word']

        os.chdir('/Users/mhee4/cloud-project')
        os.system('python stockParser.py {0}'.format(seword))

        stock_list = Stock.objects.filter(Q(name__icontains=seword)).distinct()

        context = {}
        context['search_keyword'] = seword
        context['search_list'] = stock_list

        return render(self.request, self.template_name,  context)
        # return super().form_valid(form)

stock/templates/stock/stock_detail.html
{% extends "base.html" %}
{% block title %}News Detail{% endblock %}
{% block content %}
    <div id="content">
        <h1>{{ object.title }}</h1>
        <h5><a href={{ object.url }} target="_blank">정보보기</a></h5>
        <h3> 주식정보 : {{ object.name }}</h3>
        <ul>
            <li>가격 : {{ object.price }}</li>
            <li>저장시간 : {{ object.saved_time }}</li>
    </div> 
{% endblock %}

stock/templates/stock/stock_list.html
{% extends "base.html" %}
{% block title %}Stock List{% endblock %}
{% block content %}

<div id="content">
<h1>Get Stock</h1>


<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <td>주식이름</td>
                <td>url</td>
                <td>가격</td>
                <td>게시날짜</td>
            </tr>
        </thead>
        <tbody>
            {% for stock in object_list %}
                <tr>
                    <td><a href="{% url 'stock:detail' stock.id %}">{{ stock.name }}</a></td>
                    <td>{{ stock.url }}</td>
                    <td>{{ stock.price }}</td>
                    <td>{{ stock.saved_time }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- paging link -->
    <div>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}
        [ Page {{page_obj.number}} / {{ page_obj.paginator.num_pages}} ]
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </div>
    <br><br>

            
            
    </div>


</div> 


{% endblock content %}

stock/templates/stock/stock_search.html
{% extends "base.html" %}
{% block title %}검색 페이지{% endblock %}
{% block content %}

<div id="content">
<h1>Stock Search Engine</h1>
<hr><hr>

<div>
    <h5>찾을 주식의 이름을 입력해주세요.</h5>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="search_word" value="{{ search_word }}">
        <input type="submit" value="Search">
    </form>

<br/><br/>

    {% if search_list %}
        {% for stock in search_list %}
            <h3><a href="{% url 'stock:detail' stock.id %}">{{ stock.name }}</a></h3>
            {{ stock.saved_time }}
            <p>{{ stock.price }}</p>
            <p>{{ stock.url }}</p>
        {% endfor %}
    {% elif search_keyword %}
        [{{ search_keyword }}]의 검색 결과가 없습니다.
    {% endif %}
</div>

<br><br>
{% endblock %}