api/urls.py
from django.urls import path, include
from api.views import NewsViewSet, StockViewSet, WeatherViewSet 

app_name = 'api'

news_list = NewsViewSet.as_view({ 'get' : 'list' })
news_detail = NewsViewSet.as_view({ 'get' : 'detail' })

stock_list = StockViewSet.as_view({ 'get' : 'list' })
stock_detail = StockViewSet.as_view({ 'get' : 'detail'})

weather_list = WeatherViewSet.as_view({ 'get' : 'list' })
weather_detail = WeatherViewSet.as_view({ 'get' : 'detail' })

urlpatterns = [
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('news/', news_list, name='news_list'),
    path('news/<int:pk>', news_detail, name='news_detail'),
    path('stock/', stock_list, name='stock_list'),
    path('stock/<int:pk>', stock_detail, name='stock_detail'),
    path('weather/', weather_list, name='weather_list'),
    path('weather/<int:pk>', weather_detail, name='weather_detail'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from rest_framework import routers
from news import rest_views

router = routers.DefaultRouter()
router.register(r'users', rest_views.UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('news/', include('news.urls', namespace='news')),
    path('weather/', include('weather.urls', namespace='weather')),
    path('stock/', include('stock.urls', namespace='stock')),

    path('api/', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls', namespace='api')),
]

weather/urls.py
from django.contrib import admin
from django.urls import path, include
from weather.views import WeatherLV, WeatherDV

app_name = 'weather'

urlpatterns = [
    path('', WeatherLV.as_view(), name='index'),
    path('list/', WeatherLV.as_view(), name='list'),
    path('<int:pk>/', WeatherDV.as_view(), name='detail'),
]

weather/models.py
from django.db import models

class Weather(models.Model):
    objects = models.Manager()
    city = models.CharField('CITY', max_length=50)
    date = models.TextField('DATE')
    desc = models.TextField('DESC')
    temp_min = models.TextField('TEMP_MIN')
    temp_max = models.TextField('TEMP_MAX')
    humidity = models.TextField('HUMIDITY')
    pressure = models.TextField('PRESSURE')
    deg = models.TextField('DEG')
    speed = models.TextField('SPEED')

    def __str__(self):
        return self.city + self.date + self.desc

    class Meta:
        db_table = 'weather'
        ordering = ('date',)

weather/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from weather.models import Weather

class WeatherLV(ListView):
    model = Weather
    template_name = "weather/weather_list.html"
    paginate_by = 10

class WeatherDV(DetailView):
    model = Weather




    

weather/templates/weather/weather_detail.html
{% extends "base.html" %}
{% block title %}News Detail{% endblock %}
{% block content %}
    <div id="content">
        <h1>{{ object.title }}</h1>

        <h3>도시 : {{ object.city }}</h3>
        <ul>
            <li>날짜 : {{ object.date }}</li>
            <li>날씨요약 : {{ object.desc }}</li>
            <li>최저기온 : {{ object.temp_min }}</li>
            <li>최고기온 : {{ object.temp_max }}</li>
            <li>습도 : {{ object.humidity }}</li>
            <li>기압 : {{ object.pressure }}</li>
            <li>풍향 : {{ object.deg }}</li>
            <li>풍속 : {{ object.speed }}</li>
        </ul>
    </div> 
{% endblock %}

weather/templates/weather/weather_list.html
{% extends "base.html" %}
{% block title %}News List{% endblock %}
{% block content %}
{% load static %}


<div id="content">
<h1>Weather List</h1>

<div class="row">
    <!-- <div class="col-xs-6 .col-md-4"> -->
    <h3> real weather </h3>
        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>도시</td>
                        <td>날짜</td>
                        <td>날씨요약</td>
                        <td>최저기온</td>
                        <td>최고기온</td>
                        <td>습도</td>
                        <td>기압</td>
                        <td>풍향</td>
                        <td>풍속</td>
                    </tr>
                </thead>
                <tbody>
                    {% for weather in object_list %}
                        {% if weather.date < '2021-01-30' %}
                        <tr>
                            <td>{{ weather.city }}</td>
                            <td><a href="{% url 'weather:detail' weather.id %}">{{ weather.date }}</a></td>
                            <td>{{ weather.desc }}</td>
                            <td>{{ weather.temp_min }}</td>
                            <td>{{ weather.temp_max }}</td>
                            <td>{{ weather.humidity }}</td>
                            <td>{{ weather.pressure }}</td>
                            <td>{{ weather.deg }}</td>
                            <td>{{ weather.speed }}</td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>

        </div><!--container-->
    <!-- </div>col -->

    <!-- <div class="col-xs-6 .col-md-4">  -->
    <h3> expected weather </h3>
        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>도시</td>
                        <td>날짜</td>
                        <td>날씨요약</td>
                        <td>최저기온</td>
                        <td>최고기온</td>
                        <td>습도</td>
                        <td>기압</td>
                        <td>풍향</td>
                        <td>풍속</td>
                    </tr>
                </thead>
                <tbody>
                    {% for weather in object_list %}
                        {% if weather.date > '2021-01-30' %}
                            <tr>
                                <td>{{ weather.city }}</td>
                                <td><a href="{% url 'weather:detail' weather.id %}">{{ weather.date }}</a></td>
                                <td>{{ weather.desc }}</td>
                                <td>{{ weather.temp_min }}</td>
                                <td>{{ weather.temp_max }}</td>
                                <td>{{ weather.humidity }}</td>
                                <td>{{ weather.pressure }}</td>
                                <td>{{ weather.deg }}</td>
                                <td>{{ weather.speed }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div><!--container-->
    <!-- </div>col -->
</div><!--row-->

<hr>

<!-- paging link -->
<div>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
    {% endif %}
    [ Page {{page_obj.number}} / {{ page_obj.paginator.num_pages}} ]
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
</div>

<br><br>


<div class="container">
    <div class="row">
        <div class="col-xs-6 .col-md-4">
            <h6><최고기온별 그래프></h6>
            <img src="{% static 'img/temp_max.png' %}" style="height: 300px; width: 400px;" />
        </div>
        <div class="col-xs-6 .col-md-4">
            <h6><최저기온별 그래프></h6>
            <img src="{% static 'img/temp_min.png' %}" style="height: 300px; width: 400px;" />
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 .col-md-4">
            <h6><습도별 그래프></h6>
            <img src="{% static 'img/humidity.png' %}" style="height: 300px; width: 400px;" />
        </div>
        <div class="col-xs-6 .col-md-4">
            <h6><기압별 그래프></h6>
            <img src="{% static 'img/pressure.png' %}" style="height: 300px; width: 400px;" />
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 .col-md-4">
            <h6><풍향별 그래프></h6>
            <img src="{% static 'img/deg.png' %}" style="height: 300px; width: 400px;" />
        </div>
        <div class="col-xs-6 .col-md-4">
            <h6><풍속별 그래프></h6>
            <img src="{% static 'img/speed.png' %}" style="height: 300px; width: 400px;" />
        </div>
    </div>
</div>

        
        <br><br>
    



</div> <!--main content-->


{% endblock content %}