api/urls.py
from django.urls import path, include
from api.views import NewsViewSet, StockViewSet, WeatherViewSet 

app_name = 'api'

news_list = NewsViewSet.as_view({ 'get' : 'list' })
news_detail = NewsViewSet.as_view({ 'get' : 'detail' })

stock_list = StockViewSet.as_view({ 'get' : 'list' })
stock_detail = StockViewSet.as_view({ 'get' : 'detail'})

weather_list = WeatherViewSet.as_view({ 'get' : 'list' })
weather_detail = WeatherViewSet.as_view({ 'get' : 'detail' })

urlpatterns = [
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('news/', news_list, name='news_list'),
    path('news/<int:pk>', news_detail, name='news_detail'),
    path('stock/', stock_list, name='stock_list'),
    path('stock/<int:pk>', stock_detail, name='stock_detail'),
    path('weather/', weather_list, name='weather_list'),
    path('weather/<int:pk>', weather_detail, name='weather_detail'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from rest_framework import routers
from news import rest_views

router = routers.DefaultRouter()
router.register(r'users', rest_views.UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('news/', include('news.urls', namespace='news')),
    path('weather/', include('weather.urls', namespace='weather')),
    path('stock/', include('stock.urls', namespace='stock')),

    path('api/', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls', namespace='api')),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import NewsLV, NewsDV, RefreshFormView, SearchFormView

app_name = 'news'

urlpatterns = [
    path('', NewsLV.as_view(), name='index'),
    path('list/', NewsLV.as_view(), name='list'),
    path('refresh/', RefreshFormView.as_view(), name='refresh'),
    path('<int:pk>', NewsDV.as_view(), name='detail'),
    path('search/', SearchFormView.as_view(), name='search'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>{% block title %}Django Web Programming{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/base.css' %}{% endblock %}" />
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
</head>
<body>
    <div id="header">
        <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
        <h4 class="welcome">Welcome, <a href="#">OOO</a> /
            <a href="#">Change Password</a> /
            <a href="#">Logout</a>
        </h4>
    </div>
    <div id="menu">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'weather:index' %}">Weather</a></li> 
        <li><a href="{% url 'news:refresh' %}">News</a></li> 
        <li><a href="{% url 'stock:search' %}">Stock</a></li>
        <li><a href="#">Add&bigtriangledown;</a>
            <ul>
                <li><a href="#">Weather</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Stock</a></li>
            </ul>
        </li>
        <li><a href="#">Change&bigtriangledown;</a>
            <ul>
                <li><a href="#">Weather</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Stock</a></li>
            </ul>
        </li>
        <li><a href="#">Archive</a></li>
        <li><a href="{% url 'news:search' %}">Search</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
    </div>
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Welcome to Django Page!{% endblock %}

{% load static %}
{% block extrastyle %}{% static 'css/home.css' %}{% endblock %}

{% block content %}
    <div id="content_home">
        <div id="homeimg">
            <img src="{% static 'img/django-actor-big.jpg' %}" style="height: 350px;" />
            <h4 style="margin: 0;">This is Django posered web site.</h4>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">
        &copy; This is FOOTER area.
    </div>
{% endblock footer %}